const Sequelize = require('sequelize');
const Post=require('./post');
const User=require('./user1');
const Schedule=require('./schedule');
const Schedulelist=require('./schedulelist');
const env = process.env.NODE_ENV || 'development';
const config = require('../config/config')[env];
const db = {};
const sequelize = new Sequelize(config.database, config.username, config.password, config);

db.sequelize = sequelize;
db.Post=Post;
db.User=User;
db.Schedulelist=Schedulelist;
db.Schedule=Schedule;
User.init(sequelize);
Post.init(sequelize);
Schedule.init(sequelize);
Schedulelist.init(sequelize);
module.exports = db;
